testdbt:
  outputs:
    dev:
      type: sqlserver
      driver: "{{ env_var('DBT_AZURE_DRIVER', 'ODBC Driver 18 for SQL Server') }}"
      host: "{{ env_var('DBT_AZURE_HOST') }}"
      port: 1433
      user: "{{ env_var('DBT_AZURE_USER') }}"
      password: "{{ env_var('DBT_AZURE_PWD') }}"
      database: "{{ env_var('DBT_AZURE_DB') }}"
      schema: dbo
      encrypt: yes
      TrustServerCertificate: no
      # Deine Korrektur von vorhin:
      as_columnstore: false
  target: dev